# monolith mode
target: all

ingester:
  ring:
    replication_factor: 1

common:
  storage:
    backend: s3
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      bucket_name: $LOKI_S3_BUCKET

blocks_storage:
  storage_prefix: mimirblocks

alertmanager_storage:
  storage_prefix: mimiralertmanager

ruler_storage:
  storage_prefix: mimirruler

limits:
  max_global_series_per_user: 300000
  max_label_names_per_series: 40
