#!/bin/bash
export APP_NAME=$APP_NAME
export ENV_NAME=$ENV_NAME
# DB
export GF_DATABASE_HOST=$GF_DATABASE_HOST
export GF_DATABASE_NAME=$GF_DATABASE_NAME
export GF_DATABASE_USER=$GF_DATABASE_USER
export GF_DATABASE_PASSWORD=$GF_DATABASE_PASSWORD
# DNS
export GF_SERVER_DOMAIN=$GF_SERVER_DOMAIN
export GF_SERVER_ROOT_URL=$GF_SERVER_ROOT_URL
# Start it up
docker-compose -f docker-compose.yaml up -d
